- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Box #50-∞
  - Rad #35-∞
  - Glacier #15-70
  - Cluster #10-35
  - Atlas #5-20
  - Omega #10-35
  - Shoukou #0-60
  - Europa #0-30
  - Northway #25+
  - Reach #0-7
  - Train #10-50
  - Bagel #40-76
  - Asterisk #0-60
  - Packed #5-40
  - ParkStation #5-20
  - Anchor #20-90
  - Saltern #0-35
  - Gax #10-45
  - Tortuga #50-∞
  - Edge #10-80
  - Pebble #0-30
  - Core #30-60
  - Aspid #0-70
  - Cyberiad #30+
  - Frost #15+
#  - Marathon #35-70
#  - Cog #35-70
#  - Lambda #30+
#  - Lighthouse #15-55
#  - Fland #70-∞
#  - Meta #50-∞
#  - Arena #30-80
#  - Hammurabi #50-∞
#  - Submarine #60-∞
#  - Oasis #70-∞
#  - TheHive #30-80
